language: node_js
node_js:
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"

before_script:
  - "npm i -g jsinspect"
  - "npm i -g eslint"
  - "npm i -g babel-eslint"
  - "npm i -g istanbul"

script:
  - "npm test"
